// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vakcenpzxmhiphahhavu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZha2NlbnB6eG1oaXBoYWhoYXZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMzM4NzUsImV4cCI6MjA2ODgwOTg3NX0.EZY4tb_GmHms_SF5DzimiI-HptGN6WwlrQzeiEpLa9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});